
# Set OS to linux
os: linux

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.5

before_install:
  - sudo apt-get update

# Install the library dependencies
install:
  - sudo apt-get install python3
  - pip3 install numpy opencv-python matplotlib networkx

# Run python scripts
script:
  - python3 animate_graph.py input/in5.txt
